type t = { source : string; domain : string }

let all =
  [
    { source = {|White Pages|}; domain = {|www.whitepages.com.au|} };
    { source = {|QQ Mail|}; domain = {|mail.qq.com|} };
    { source = {|eo|}; domain = {|eo.st|} };
    { source = {|Toolbarhome|}; domain = {|www.toolbarhome.com|} };
    { source = {|YouGoo|}; domain = {|www.yougoo.fr|} };
    { source = {|Walhello|}; domain = {|www.walhello.info|} };
    { source = {|Tixuma|}; domain = {|www.tixuma.de|} };
    { source = {|Hyves|}; domain = {|hyves.nl|} };
    { source = {|PriceRunner|}; domain = {|www.pricerunner.co.uk|} };
    { source = {|Euroseek|}; domain = {|www.euroseek.com|} };
    { source = {|Web.nl|}; domain = {|www.web.nl|} };
    { source = {|360.cn|}; domain = {|so.360.cn|} };
    { source = {|Seznam|}; domain = {|search.seznam.cz|} };
    { source = {|Nigma|}; domain = {|nigma.ru|} };
    { source = {|Wirtualna Polska|}; domain = {|szukaj.wp.pl|} };
    { source = {|Google Product Search|}; domain = {|google.ac/products|} };
    { source = {|Picsearch|}; domain = {|www.picsearch.com|} };
    { source = {|Suchnase|}; domain = {|www.suchnase.de|} };
    { source = {|WebSearch|}; domain = {|www.websearch.com|} };
    { source = {|Lycos|}; domain = {|search.lycos.com|} };
    { source = {|Conduit|}; domain = {|search.conduit.com|} };
    { source = {|StackOverflow|}; domain = {|stackoverflow.com|} };
    { source = {|GitHub|}; domain = {|github.com|} };
    { source = {|FriendFeed|}; domain = {|friendfeed.com|} };
    { source = {|Flickr|}; domain = {|flickr.com|} };
    { source = {|Google+|}; domain = {|url.google.com|} };
    { source = {|APOLL07|}; domain = {|apollo7.de|} };
    { source = {|Douban|}; domain = {|douban.com|} };
    { source = {|Pocket|}; domain = {|getpocket.com|} };
    { source = {|Doubleclick|}; domain = {|ad.doubleclick.net|} };
    { source = {|Exalead|}; domain = {|www.exalead.fr|} };
    { source = {|Sharelook|}; domain = {|www.sharelook.fr|} };
    { source = {|Adam Internet|}; domain = {|webmail.adam.com.au|} };
    { source = {|Friendster|}; domain = {|friendster.com|} };
    { source = {|2degrees|}; domain = {|webmail.2degreesbroadband.co.nz|} };
    { source = {|ZEDO|}; domain = {|zedo.com|} };
    { source = {|Outlook.com|}; domain = {|mail.live.com|} };
    { source = {|1&1|}; domain = {|search.1and1.com|} };
    { source = {|URL.ORGanizier|}; domain = {|www.url.org|} };
    { source = {|Google|}; domain = {|support.google.com|} };
    { source = {|Snapdo|}; domain = {|search.snapdo.com|} };
    { source = {|Bebo|}; domain = {|bebo.com|} };
    { source = {|Biglobe|}; domain = {|cgi.search.biglobe.ne.jp|} };
    { source = {|1und1|}; domain = {|search.1und1.de|} };
    { source = {|BlackPlanet|}; domain = {|blackplanet.com|} };
    { source = {|Findwide|}; domain = {|search.findwide.com|} };
    { source = {|Digg|}; domain = {|digg.com|} };
    { source = {|Eurip|}; domain = {|www.eurip.com|} };
    { source = {|SearchCanvas|}; domain = {|www.searchcanvas.com|} };
    { source = {|Sapo|}; domain = {|pesquisa.sapo.pt|} };
    { source = {|Yieldmo|}; domain = {|yieldmo.com|} };
    { source = {|ABCsøk|}; domain = {|abcsolk.no|} };
    { source = {|Gaia Online|}; domain = {|gaiaonline.com|} };
    { source = {|blekko|}; domain = {|blekko.com|} };
    { source = {|Vodafone|}; domain = {|webmail.vodafone.co.nz|} };
    { source = {|qip|}; domain = {|search.qip.ru|} };
    { source = {|Hooseek.com|}; domain = {|www.hooseek.com|} };
    { source = {|Tumblr|}; domain = {|tumblr.com|} };
    { source = {|GAIS|}; domain = {|gais.cs.ccu.edu.tw|} };
    { source = {|AllTheWeb|}; domain = {|www.alltheweb.com|} };
    { source = {|Terra|}; domain = {|buscador.terra.es|} };
    { source = {|Buzznet|}; domain = {|buzznet.com|} };
    { source = {|Searchy|}; domain = {|www.searchy.co.uk|} };
    { source = {|Commander|}; domain = {|webmail.commander.net.au|} };
    { source = {|Twingly|}; domain = {|www.twingly.com|} };
    { source = {|Yandex|}; domain = {|yandex.ru|} };
    { source = {|Najdi|}; domain = {|www.najdi.si|} };
    { source = {|Sociomantic Labs|}; domain = {|sociomantic.com|} };
    { source = {|Netlog|}; domain = {|netlog.com|} };
    { source = {|Volny|}; domain = {|web.volny.cz|} };
    { source = {|Criteo|}; domain = {|cas.jp.as.criteo.com|} };
    { source = {|dmoz|}; domain = {|dmoz.org|} };
    { source = {|Bing|}; domain = {|bing.com|} };
    { source = {|Altavista|}; domain = {|www.altavista.com|} };
    { source = {|Kataweb|}; domain = {|www.kataweb.it|} };
    { source = {|Charter|}; domain = {|www.charter.net|} };
    { source = {|Startpagina|}; domain = {|startgoogle.startpagina.nl|} };
    { source = {|Search.ch|}; domain = {|www.search.ch|} };
    { source = {|Uludag Sozluk|}; domain = {|uludagsozluk.com|} };
    { source = {|Orkut|}; domain = {|orkut.com|} };
    { source = {|UKR.net|}; domain = {|search.ukr.net|} };
    { source = {|Sonico.com|}; domain = {|sonico.com|} };
    { source = {|Comcast|}; domain = {|serach.comcast.net|} };
    { source = {|Yandex Images|}; domain = {|images.yandex.ru|} };
    { source = {|Vindex|}; domain = {|www.vindex.nl|} };
    { source = {|Zoho|}; domain = {|mail.zoho.com|} };
    { source = {|SteelHouse|}; domain = {|steelhousemedia.com|} };
    { source = {|Geona|}; domain = {|geona.net|} };
    { source = {|Excite|}; domain = {|search.excite.it|} };
    { source = {|1.cz|}; domain = {|1.cz|} };
    { source = {|Vimeo|}; domain = {|vimeo.com|} };
    {
      source = {|Rubicon Project|};
      domain = {|optimized-by.rubiconproject.com|};
    };
    { source = {|Yasni|}; domain = {|www.yasni.de|} };
    { source = {|Badoo|}; domain = {|badoo.com|} };
    { source = {|Tiscali|}; domain = {|search.tiscali.it|} };
    { source = {|Inbox.com|}; domain = {|inbox.com|} };
    { source = {|Orange Webmail|}; domain = {|orange.fr/webmail|} };
    { source = {|Blogpulse|}; domain = {|www.blogpulse.com|} };
    { source = {|Delfi latvia|}; domain = {|smart.delfi.lv|} };
    { source = {|iPrimus|}; domain = {|webmail.iprimus.com.au|} };
    { source = {|Mail.ru|}; domain = {|my.mail.ru|} };
    { source = {|Google News|}; domain = {|news.google.ac|} };
    { source = {|Delicious|}; domain = {|delicious.com|} };
    { source = {|Sonobi|}; domain = {|sonobi.com|} };
    { source = {|Road Runner Search|}; domain = {|search.rr.com|} };
    { source = {|Fast Browser Search|}; domain = {|www.fastbrowsersearch.com|} };
    { source = {|WAYN|}; domain = {|wayn.com|} };
    { source = {|Weibo|}; domain = {|weibo.com|} };
    { source = {|Windows Live Spaces|}; domain = {|login.live.com|} };
    { source = {|Clix|}; domain = {|pesquisa.clix.pt|} };
    { source = {|T-Online|}; domain = {|suche.t-online.de|} };
    { source = {|Ask Toolbar|}; domain = {|search.tb.ask.com|} };
    { source = {|Flyingbird|}; domain = {|inspsearch.com|} };
    { source = {|Yahoo!|}; domain = {|finance.yahoo.com|} };
    { source = {|Alexa|}; domain = {|alexa.com|} };
    { source = {|Jungle Key|}; domain = {|junglekey.com|} };
    { source = {|Gmail|}; domain = {|mail.google.com|} };
    { source = {|Optus Zoo|}; domain = {|webmail.optuszoo.com.au|} };
    { source = {|Web.de|}; domain = {|suche.web.de|} };
    { source = {|Odnoklassniki|}; domain = {|odnoklassniki.ru|} };
    { source = {|GMX|}; domain = {|suche.gmx.net|} };
    { source = {|Freshweather|}; domain = {|www.fresh-weather.com|} };
    { source = {|Quora|}; domain = {|quora.com|} };
    { source = {|AppNexus|}; domain = {|ib.adnxs.com|} };
    { source = {|Onet|}; domain = {|szukaj.onet.pl|} };
    { source = {|Geni|}; domain = {|geni.com|} };
    { source = {|Naver Images|}; domain = {|image.search.naver.com|} };
    { source = {|Qzone|}; domain = {|qzone.qq.com|} };
    { source = {|Mozbot|}; domain = {|www.mozbot.fr|} };
    { source = {|Adform|}; domain = {|adform.net|} };
    { source = {|Blogdigger|}; domain = {|www.blogdigger.com|} };
    { source = {|Netspace|}; domain = {|webmail.netspace.net.au|} };
    { source = {|Apontador|}; domain = {|apontador.com.br|} };
    { source = {|Jungle Spider|}; domain = {|www.jungle-spider.de|} };
    { source = {|Mozo|}; domain = {|mozo.com.au|} };
    { source = {|Zapmeta|}; domain = {|www.zapmeta.com|} };
    { source = {|MySearch|}; domain = {|www.mysearch.com|} };
    { source = {|X-recherche|}; domain = {|www.x-recherche.com|} };
    { source = {|Lo.st|}; domain = {|lo.st|} };
    { source = {|TrovaRapido|}; domain = {|www.trovarapido.com|} };
    { source = {|Dodo|}; domain = {|webmail.dodo.com.au|} };
    { source = {|Flix|}; domain = {|www.flix.de|} };
    { source = {|Flashtalking|}; domain = {|flashtalking.com|} };
    { source = {|Nasza-klasa.pl|}; domain = {|nk.pl|} };
    { source = {|AOL Mail|}; domain = {|mail.aol.com|} };
    { source = {|Virgilio|}; domain = {|ricerca.virgilio.it|} };
    { source = {|Rambler|}; domain = {|nova.rambler.ru|} };
    { source = {|Atlas|}; domain = {|searchatlas.centrum.cz|} };
    { source = {|Austronaut|}; domain = {|www2.austronaut.at|} };
    { source = {|Xanga|}; domain = {|xanga.com|} };
    { source = {|vKruguDruzei.ru|}; domain = {|vkrugudruzei.ru|} };
    { source = {|Friends Reunited|}; domain = {|friendsreunited.com|} };
    { source = {|Nifty|}; domain = {|search.nifty.com|} };
    { source = {|Plaxo|}; domain = {|plaxo.com|} };
    { source = {|Sizmek|}; domain = {|bs.serving-sys.com|} };
    { source = {|ONE by AOL|}; domain = {|nexage.com|} };
    { source = {|Gomeo|}; domain = {|www.gomeo.com|} };
    { source = {|BidSwitch|}; domain = {|bidswitch.net|} };
    { source = {|Yahoo! Images|}; domain = {|image.yahoo.cn|} };
    { source = {|ITU Sozluk|}; domain = {|itusozluk.com|} };
    { source = {|Instagram|}; domain = {|instagram.com|} };
    { source = {|AOL|}; domain = {|search.aol.com|} };
    { source = {|Compuserve|}; domain = {|websearch.cs.com|} };
    { source = {|Free|}; domain = {|search.free.fr|} };
    { source = {|Reddit|}; domain = {|reddit.com|} };
    { source = {|Metager2|}; domain = {|metager2.de|} };
    { source = {|Tuenti|}; domain = {|tuenti.com|} };
    { source = {|Rakuten|}; domain = {|websearch.rakuten.co.jp|} };
    { source = {|126 Mail|}; domain = {|mail.126.com|} };
    { source = {|Centrum|}; domain = {|serach.centrum.cz|} };
    { source = {|Dalesearch|}; domain = {|www.dalesearch.com|} };
    { source = {|Freecause|}; domain = {|search.freecause.com|} };
    { source = {|Viadeo|}; domain = {|viadeo.com|} };
    { source = {|Bing Images|}; domain = {|bing.com/images/search|} };
    { source = {|Softonic|}; domain = {|search.softonic.com|} };
    { source = {|ICQ|}; domain = {|www.icq.com|} };
    { source = {|Gule Sider|}; domain = {|www.gulesider.no|} };
    { source = {|Winamp|}; domain = {|search.winamp.com|} };
    { source = {|Paperball|}; domain = {|www.paperball.de|} };
    { source = {|Gigablast|}; domain = {|www.gigablast.com|} };
    { source = {|Inci Sozluk|}; domain = {|inci.sozlukspot.com|} };
    { source = {|Outbrain|}; domain = {|paid.outbrain.com|} };
    { source = {|Plista|}; domain = {|farm.plista.com|} };
    { source = {|Neti|}; domain = {|www.neti.ee|} };
    { source = {|LifeStreet|}; domain = {|lfstmedia.com|} };
    { source = {|Finderoo|}; domain = {|www.finderoo.com|} };
    { source = {|Virgin|}; domain = {|webmail.virginbroadband.com.au|} };
    { source = {|Latne|}; domain = {|www.latne.lv|} };
    { source = {|Meinestadt|}; domain = {|www.meinestadt.de|} };
    { source = {|Google Video|}; domain = {|video.google.com|} };
    { source = {|Babylon|}; domain = {|search.babylon.com|} };
    { source = {|Mixi|}; domain = {|mixi.jp|} };
    { source = {|Twitter|}; domain = {|twitter.com|} };
    { source = {|earthlink|}; domain = {|search.earthlink.net|} };
    { source = {|Pinterest|}; domain = {|pinterest.com|} };
    { source = {|Online.no|}; domain = {|online.no|} };
    { source = {|Foursquare|}; domain = {|foursquare.com|} };
    { source = {|Skynet|}; domain = {|www.skynet.be|} };
    { source = {|Amazon|}; domain = {|amazon.com|} };
    { source = {|Crawler|}; domain = {|www.crawler.com|} };
    { source = {|Voila|}; domain = {|search.ke.voila.fr|} };
    { source = {|Orange|}; domain = {|busca.orange.es|} };
    { source = {|Apollo Latvia|}; domain = {|apollo.lv/portal/search/|} };
    { source = {|Zoeken|}; domain = {|www.zoeken.nl|} };
    { source = {|Vinden|}; domain = {|www.vinden.nl|} };
    { source = {|163 Mail|}; domain = {|mail.163.com|} };
    { source = {|Google Images|}; domain = {|google.ac/imgres|} };
    { source = {|Opplysningen 1881|}; domain = {|www.1881.no|} };
    { source = {|Classmates|}; domain = {|classmates.com|} };
    { source = {|Jivox|}; domain = {|jivox.com|} };
    { source = {|Naver Mail|}; domain = {|mail.naver.com|} };
    { source = {|Arianna|}; domain = {|arianna.libero.it|} };
    { source = {|Skyrock|}; domain = {|skyrock.com|} };
    { source = {|Eksi Sozluk|}; domain = {|Sozluk.com|} };
    { source = {|goo|}; domain = {|search.goo.ne.jp|} };
    { source = {|Hacker News|}; domain = {|news.ycombinator.com|} };
    { source = {|Metager|}; domain = {|meta.rrzn.uni-hannover.de|} };
    { source = {|Witch|}; domain = {|www.witch.de|} };
    { source = {|suche.info|}; domain = {|suche.info|} };
    { source = {|SoSoDesk|}; domain = {|sosodesktop.com|} };
    { source = {|Fixsuche|}; domain = {|www.fixsuche.de|} };
    { source = {|Everyclick|}; domain = {|www.everyclick.com|} };
    { source = {|Weborama|}; domain = {|www.weborama.com|} };
    { source = {|Freenet|}; domain = {|webmail.freenet.de|} };
    { source = {|Icerockeet|}; domain = {|blogs.icerocket.com|} };
    { source = {|Vkontakte|}; domain = {|vk.com|} };
    { source = {|Firstfind|}; domain = {|www.firstsfind.com|} };
    { source = {|SourceForge|}; domain = {|sourceforge.net|} };
    { source = {|Donanimhaber|}; domain = {|donanimhaber.com|} };
    { source = {|OpenX|}; domain = {|us-ads.openx.net|} };
    { source = {|Qualigo|}; domain = {|www.qualigo.at|} };
    { source = {|Zoohoo|}; domain = {|zoohoo.cz|} };
    { source = {|Aport|}; domain = {|sm.aport.ru|} };
    { source = {|Tribal Fusion|}; domain = {|cdnx.tribalfusion.com|} };
    { source = {|Ecosia|}; domain = {|ecosia.org|} };
    { source = {|Nate|}; domain = {|search.nate.com|} };
    { source = {|Last.fm|}; domain = {|lastfm.ru|} };
    { source = {|Jyxo|}; domain = {|jyxo.1188.cz|} };
    { source = {|Flixster|}; domain = {|flixster.com|} };
    { source = {|Youtube|}; domain = {|youtube.com|} };
    { source = {|Eniro|}; domain = {|www.eniro.se|} };
    { source = {|Needtofind|}; domain = {|ko.search.need2find.com|} };
    { source = {|Disqus|}; domain = {|redirect.disqus.com|} };
    { source = {|Eyeota|}; domain = {|eyeota.net|} };
    { source = {|PubMatic|}; domain = {|sshowads.pubmatic.com|} };
    { source = {|Holmes|}; domain = {|holmes.ge|} };
    { source = {|Looksmart|}; domain = {|www.looksmart.com|} };
    { source = {|Yatedo|}; domain = {|www.yatedo.com|} };
    { source = {|Telstra|}; domain = {|search.media.telstra.com.au|} };
    { source = {|El Mundo|}; domain = {|ariadna.elmundo.es|} };
    { source = {|Baidu|}; domain = {|www.baidu.com|} };
    { source = {|Trusted-Search|}; domain = {|www.trusted--search.com|} };
    { source = {|WeeWorld|}; domain = {|weeworld.com|} };
    { source = {|MetaCrawler.de|}; domain = {|s1.metacrawler.de|} };
    { source = {|maailm|}; domain = {|www.maailm.com|} };
    { source = {|RPMFind|}; domain = {|rpmfind.net|} };
    { source = {|British Telecommunications|}; domain = {|search.bt.com|} };
    { source = {|WWW|}; domain = {|search.www.ee|} };
    { source = {|AdRoll|}; domain = {|adroll.com|} };
    { source = {|Hit-Parade|}; domain = {|req.-hit-parade.com|} };
    { source = {|Tagged|}; domain = {|login.tagged.com|} };
    { source = {|Paper.li|}; domain = {|paper.li|} };
    { source = {|AudienceScience|}; domain = {|wunderloop.net|} };
    { source = {|Marktplaats|}; domain = {|www.marktplaats.nl|} };
    { source = {|StickyADS.tv|}; domain = {|stickyadstv.com|} };
    { source = {|MyLife|}; domain = {|mylife.ru|} };
    { source = {|Yahoo! Mail|}; domain = {|mail.yahoo.net|} };
    { source = {|Search This|}; domain = {|www.searchthis.com|} };
    { source = {|XING|}; domain = {|xing.com|} };
    { source = {|Monstercrawler|}; domain = {|www.monstercrawler.com|} };
    { source = {|Habbo|}; domain = {|habbo.com|} };
    { source = {|MyHeritage|}; domain = {|myheritage.com|} };
    { source = {|La Toile Du Quebec Via Google|}; domain = {|www.toile.com|} };
    { source = {|Gnadenmeer|}; domain = {|www.gnadenmeer.de|} };
    { source = {|Ask|}; domain = {|ask.com|} };
    { source = {|Yippy|}; domain = {|search.yippy.com|} };
    { source = {|Bigpond|}; domain = {|webmail.bigpond.com|} };
    { source = {|Seznam Mail|}; domain = {|email.seznam.cz|} };
    { source = {|Plazoo|}; domain = {|www.plazoo.com|} };
    { source = {|Goyellow.de|}; domain = {|www.goyellow.de|} };
    { source = {|Fluct|}; domain = {|adingo.jp|} };
    { source = {|LinkedIn|}; domain = {|linkedin.com|} };
    { source = {|PeoplePC|}; domain = {|search.peoplepc.com|} };
    { source = {|I.ua|}; domain = {|search.i.ua|} };
    { source = {|Mixpo|}; domain = {|mixpo.com|} };
    { source = {|Hotbot|}; domain = {|www.hotbot.com|} };
    { source = {|Daum Mail|}; domain = {|mail2.daum.net|} };
    { source = {|Cuil|}; domain = {|www.cuil.com|} };
    { source = {|Francite|}; domain = {|recherche.francite.com|} };
    { source = {|Maxwebsearch|}; domain = {|maxwebsearch.com|} };
    { source = {|Sovrn|}; domain = {|lijit.com|} };
    { source = {|Daum|}; domain = {|search.daum.net|} };
    { source = {|Suchmaschine.com|}; domain = {|www.suchmaschine.com|} };
    { source = {|Myspace|}; domain = {|myspace.com|} };
    { source = {|Instela|}; domain = {|instela.com|} };
    { source = {|Forestle|}; domain = {|forestle.org|} };
    { source = {|Alice Adsl|}; domain = {|rechercher.aliceadsl.fr|} };
    { source = {|Zoek|}; domain = {|www3.zoek.nl|} };
    {
      source = {|Certified-Toolbar|};
      domain = {|search.certified-toolbar.com|};
    };
    { source = {|MicroAd|}; domain = {|microad.jp|} };
    { source = {|IXquick|}; domain = {|ixquick.com|} };
    { source = {|Trouvez.com|}; domain = {|www.trouvez.com|} };
    { source = {|Globososo|}; domain = {|searches.globososo.com|} };
    { source = {|Startsiden|}; domain = {|www.startsiden.no|} };
    { source = {|LiveJournal|}; domain = {|livejournal.ru|} };
    { source = {|Daemon search|}; domain = {|daemon-search.com|} };
    { source = {|Hocam.com|}; domain = {|hocam.com|} };
    { source = {|Sogou|}; domain = {|www.sougou.com|} };
    { source = {|Renren|}; domain = {|renren.com|} };
    { source = {|Mamma|}; domain = {|www.mamma.com|} };
    { source = {|Fireball|}; domain = {|www.fireball.de|} };
    { source = {|Neustar AdAdvisor|}; domain = {|adadvisor.net|} };
    { source = {|Technorati|}; domain = {|technorati.com|} };
    { source = {|myYearbook|}; domain = {|myyearbook.com|} };
    { source = {|Poisk.ru|}; domain = {|poisk.ru|} };
    { source = {|Mister Wong|}; domain = {|www.mister-wong.com|} };
    { source = {|MoiKrug.ru|}; domain = {|moikrug.ru|} };
    { source = {|Casale Media|}; domain = {|casalemedia.com|} };
    { source = {|Google Blogsearch|}; domain = {|blogsearch.google.ac|} };
    { source = {|The Smart Search|}; domain = {|thesmartsearch.net|} };
    { source = {|all.by|}; domain = {|all.by|} };
    { source = {|Multiply|}; domain = {|multiply.com|} };
    { source = {|Ilse|}; domain = {|www.ilse.nl|} };
    { source = {|DasOertliche|}; domain = {|www.dasoertliche.de|} };
    { source = {|Genieo|}; domain = {|search.genieo.com|} };
    { source = {|Zhongsou|}; domain = {|p.zhongsou.com|} };
    { source = {|Kvasir|}; domain = {|www.kvasir.no|} };
    { source = {|kununu|}; domain = {|kununu.com|} };
    { source = {|StudiVZ|}; domain = {|studivz.net|} };
    { source = {|I-play|}; domain = {|start.iplay.com|} };
    { source = {|iiNet|}; domain = {|webmail.iinet.net.au|} };
    { source = {|DasTelefonbuch|}; domain = {|www1.dastelefonbuch.de|} };
    { source = {|Tut.by|}; domain = {|search.tut.by|} };
    { source = {|Interia|}; domain = {|www.google.interia.pl|} };
    { source = {|Naver|}; domain = {|search.naver.com|} };
    { source = {|Facebook|}; domain = {|facebook.com|} };
    { source = {|Yam|}; domain = {|search.yam.com|} };
    { source = {|Acoon|}; domain = {|www.acoon.de|} };
    { source = {|Searchalot|}; domain = {|searchalot.com|} };
    { source = {|StumbleUpon|}; domain = {|stumbleupon.com|} };
    { source = {|Taboola|}; domain = {|trc.taboola.com|} };
    { source = {|Abacho|}; domain = {|www.abacho.de|} };
    { source = {|Acuity Ads|}; domain = {|acuityplatform.com|} };
    { source = {|Meta|}; domain = {|meta.ua|} };
    { source = {|Cyworld|}; domain = {|global.cyworld.com|} };
    { source = {|canoe.ca|}; domain = {|web.canoe.ca|} };
    { source = {|DuckDuckGo|}; domain = {|duckduckgo.com|} };
    { source = {|Identi.ca|}; domain = {|identi.ca|} };
    { source = {|Bluewin|}; domain = {|search.bluewin.ch|} };
    { source = {|Taringa!|}; domain = {|taringa.net|} };
    { source = {|Teoma|}; domain = {|www.teoma.com|} };
    { source = {|Mynet Mail|}; domain = {|mail.mynet.com|} };
    { source = {|InfoSpace|}; domain = {|infospace.com|} };
    { source = {|arama|}; domain = {|arama.com|} };
    { source = {|Delfi|}; domain = {|otsing.delfi.ee|} };
    { source = {|TalkTalk|}; domain = {|www.talktalk.co.uk|} };
    { source = {|hi5|}; domain = {|hi5.com|} };
    { source = {|HighBeam|}; domain = {|www.highbeam.com|} };
    { source = {|uol.com.br|}; domain = {|busca.uol.com.br|} };
    { source = {|Westnet|}; domain = {|webmail.westnet.com.au|} };
    { source = {|Fotolog|}; domain = {|fotolog.com|} };
    { source = {|Arcor|}; domain = {|www.arcor.de|} };
    { source = {|Search.com|}; domain = {|www.search.com|} };
  ]
